name: Build
on: push
jobs:
  linux-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packages
        run: |
          sudo apt-get update && sudo apt-get install -y wget cmake gnupg2 ninja-build build-essential unzip libx11-dev libxcomposite-dev libxext-dev libasound2-dev libfontconfig1-dev libglu1-mesa-dev mesa-common-dev libcurl4-openssl-dev libomp-dev clang
      - name: Build Vcpkg dependencies
        env:
          VCPKG_TARGET_TRIPLET: x64-linux
          VCPKG_HOST_TRIPLET: x64-linux
        run: |
          cd "$VCPKG_INSTALLATION_ROOT"
          ./vcpkg install fftw3[avx2] sleef[dft] pffft juce[core]
      - name: Get KFR7 binaries
        env:
          TMP_DIR: ${{ runner.temp }}
          KFR_VER: 7.0.1
        run: |
          curl -o "$TMP_DIR/kfr.zip" -L "https://github.com/kfrlib/kfr/releases/download/$KFR_VER/kfr-linux-x86_64.zip"
          unzip "$TMP_DIR/kfr.zip" -d "${TMP_DIR}/kfr"
          ls -la "${TMP_DIR}/kfr/kfr-linux-x86_64"
      - name: Install IPP & MKL binaries
        run: |
          wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo gpg --dearmor -o /usr/share/keyrings/intel-oneapi-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-ipp intel-oneapi-ipp-devel
          sudo apt-get install -y intel-oneapi-mkl intel-oneapi-mkl-devel
      - name: Build benchmark
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -GNinja "-DCMAKE_PREFIX_PATH=${TMP_DIR}/kfr/kfr-linux-x86_64/lib/cmake;$VCPKG_INSTALLATION_ROOT/installed/x64-linux/share;/opt/intel/oneapi/ipp/latest/lib/cmake;/opt/intel/oneapi/mkl/latest/lib/cmake" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          ninja -C build
          ls -la build
          file build/fft_benchmark_{fftw,kfr,ipp,mkl,sleef,kissfft,pffft,juce}
          mkdir -p "${{ github.workspace }}/dist"
          cp build/fft_benchmark_{fftw,kfr,ipp,mkl,sleef,kissfft,pffft,juce} "${{ github.workspace }}/dist"
      - name: Binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64
          path: ${{ github.workspace }}/dist
      - name: Upload buildtrees
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-buildtrees
          retention-days: 10
          path: |
            /usr/local/share/vcpkg/buildtrees

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packages
        run: |
          sudo apt-get update && sudo apt-get install -y wget cmake gnupg2 ninja-build build-essential unzip libx11-dev libxcomposite-dev libxext-dev libasound2-dev libfontconfig1-dev libglu1-mesa-dev mesa-common-dev libcurl4-openssl-dev libomp-dev clang
      - name: Build Vcpkg dependencies
        env:
          VCPKG_TARGET_TRIPLET: arm64-linux
          VCPKG_HOST_TRIPLET: arm64-linux
        run: |
          cd "$VCPKG_INSTALLATION_ROOT"
          ./vcpkg install fftw3[neon] sleef[dft] pffft juce[core]
      - name: Get KFR7 binaries
        env:
          TMP_DIR: ${{ runner.temp }}
          KFR_VER: 7.0.1
        run: |
          curl -o "$TMP_DIR/kfr.zip" -L "https://github.com/kfrlib/kfr/releases/download/$KFR_VER/kfr-linux-arm64.zip"
          unzip "$TMP_DIR/kfr.zip" -d "${TMP_DIR}/kfr"
          ls -la "${TMP_DIR}/kfr/kfr-linux-arm64"
      - name: Build benchmark
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -GNinja "-DCMAKE_PREFIX_PATH=${TMP_DIR}/kfr/kfr-linux-arm64/lib/cmake;$VCPKG_INSTALLATION_ROOT/installed/arm64-linux/share" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          ninja -C build
          ls -la build
          file build/fft_benchmark_{fftw,kfr,sleef,kissfft,pffft,juce}
          mkdir -p "${{ github.workspace }}/dist"
          cp build/fft_benchmark_{fftw,kfr,sleef,kissfft,pffft,juce} "${{ github.workspace }}/dist"
      - name: Binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: ${{ github.workspace }}/dist
      - name: Upload buildtrees
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-buildtrees-arm64
          retention-days: 10
          path: |
            /usr/local/share/vcpkg/buildtrees

  macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Packages
        run: |
          brew install cmake ninja libomp
      - name: Build Vcpkg dependencies
        env:
          VCPKG_TARGET_TRIPLET: arm64-osx
          VCPKG_HOST_TRIPLET: arm64-osx
        run: |
          cd "$VCPKG_INSTALLATION_ROOT"
          ./vcpkg install fftw3[neon] sleef[dft] pffft juce[core] --allow-unsupported
      - name: Get KFR7 binaries
        env:
          TMP_DIR: ${{ runner.temp }}
          KFR_VER: 7.0.1
        run: |
          curl -o "$TMP_DIR/kfr.zip" -L "https://github.com/kfrlib/kfr/releases/download/$KFR_VER/kfr-macos-arm64.zip"
          unzip "$TMP_DIR/kfr.zip" -d "${TMP_DIR}/kfr"
          ls -la "${TMP_DIR}/kfr/kfr-macos-arm64"
      - name: Build benchmark
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          cmake -B build -S . -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_BUILD_TYPE=Release -GNinja "-DCMAKE_PREFIX_PATH=${TMP_DIR}/kfr/kfr-macos-arm64/lib/cmake;$VCPKG_INSTALLATION_ROOT/installed/arm64-osx/share"
          ninja -C build
          ls -la build
          file build/fft_benchmark_{fftw,kfr,sleef,kissfft,pffft,juce}
          mkdir -p "${{ github.workspace }}/dist"
          cp build/fft_benchmark_{fftw,kfr,sleef,kissfft,pffft,juce} "${{ github.workspace }}/dist"
      - name: Binaries
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: ${{ github.workspace }}/dist
      - name: Upload buildtrees
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-buildtrees-macos-arm64
          retention-days: 10
          path: |
            /usr/local/share/vcpkg/buildtrees

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Vcpkg dependencies
        run: |
          cd "$env:VCPKG_INSTALLATION_ROOT"
          .\vcpkg install --triplet=x64-windows-static-md --host-triplet=x64-windows-static-md fftw3[avx2] sleef[dft] pffft juce[core]
      - name: Get KFR7 binaries
        env:
          TMP_DIR: ${{ runner.temp }}
          KFR_VER: 7.0.1
        run: |
          curl.exe -o "$env:TMP_DIR\kfr.zip" -L "https://github.com/kfrlib/kfr/releases/download/$env:KFR_VER/kfr-windows-x86_64.zip"
          Expand-Archive -Path "$env:TMP_DIR\kfr.zip" -DestinationPath "$env:TMP_DIR\kfr"
      - name: Install IPP & MKL
        shell: cmd
        run: |
          curl.exe --output %TEMP%\webimage.exe --url "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/1f18901e-877d-469d-a41a-a10f11b39336/intel-oneapi-base-toolkit-2025.3.0.372_offline.exe" --retry 5 --retry-delay 5
          start /b /wait %TEMP%\webimage.exe -s -x -f webimage_extracted --log extract.log
          del %TEMP%\webimage.exe
          webimage_extracted\bootstrapper.exe -s --action install --components=intel.oneapi.win.ipp.devel:intel.oneapi.win.mkl.devel --eula=accept -p=NEED_VS2019_INTEGRATION=0 -p=NEED_VS2022_INTEGRATION=0 --log-dir=.
          rd /s/q "webimage_extracted"
      - name: Build benchmark
        env:
          TMP_DIR: ${{ runner.temp }}
        run: |
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64 -HostArch amd64
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -GNinja "-DCMAKE_PREFIX_PATH=$env:TMP_DIR/kfr/kfr-windows-x86_64/lib/cmake;$env:VCPKG_INSTALLATION_ROOT/installed/x64-windows-static-md/share;C:/Program Files (x86)/Intel/oneAPI/ipp/latest/lib/cmake;C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/cmake" -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe"
          ninja -C build
          New-Item -ItemType Directory -Force -Path "${{ github.workspace }}\dist"
          Copy-Item build\fft_benchmark_*.exe "${{ github.workspace }}\dist"
      - name: Binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: ${{ github.workspace }}/dist
      - name: Upload buildtrees
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-buildtrees-windows
          retention-days: 10
          path: |
            C:\vcpkg\buildtrees
